# Server Port
server.port=8080

# MySQL Connection Settings
spring.datasource.url=jdbc:mysql://localhost:3306/pangasmart_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234

# Hibernate & JPA Settings
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#Weka hii kuzuia JPA isigome wakati tunatengeneza Entities
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration


# ? FEATURE FLAGS (SWICHI ZA BIASHARA & MALIPO)
# Ziko FALSE kwa sasa (BURE), tukitaka kuanza kutoza tutazibadili kuwa TRUE
pangasmart.monetization.charge-landlord-listing=false
pangasmart.monetization.charge-tenant-booking=false
pangasmart.monetization.free-listing-limit=1
# Ruhusu Railway HTTPS reverse proxy itunze Login Session Cookies
server.forward-headers-strategy=framework
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.same-site=none

# Onyesha Hibernate SQL logs ili uone kama DB inasoma user wakati wa login
# Ruhusu ukubwa wa file moja hadi 50MB
spring.servlet.multipart.max-file-size=50MB

# Ruhusu ukubwa wa jumla wa request yote hadi 50MB
spring.servlet.multipart.max-request-size=50MB
spring.jpa.show-sql=true